### ISSUE TITLE
OW2 temporarily suspended

### ISSUE THREAD

**Issue by dougg0k** [foryVERX/Overwatch-Server-Selector#22]
Hi,

I've been trying geofence techniques, but I didnt with your tool yet, but straight to the firewall (simplewall), I blocked the IPs from the list and only left the ones that I wanted to connect. It was ANY protocol and ANY direction, to remote addresses.

Yet, sometimes I get that it found the server message in OW2, it doesnt leave the queue screen and seconds later, I get suspended, instead of just failing or going to another, this is on competitive of course.

Would you have any idea why?

Your tests seem to be on Quick play, have you tried on competitive?

Quick Play and Training, I get the message: Failed to connect to server. It doesnt redirect. If yours do, there must be a reason. 

All of this is on solo queue btw.

@foryVERX 

https://github.com/dougg0k/gaming_os_tweaker/blob/main/scripts/optional_helpers/geofence_helper.ps1

---

Could it be related to Reject vs Drop?

DROP - Does not respond, just ignore the packet.
REJECT - Send a ICMP response back saying no.

---

It seems that Windows Firewall does DROP by default, waiting on the answer from simplewall. There are indications that is also drop, but it doesnt make sense why it's not working.

https://github.com/henrypp/simplewall/issues/1586 

---

Ok, so it doesnt seem to be related to that, I just went back to windows firewall, same behavior happened. But in the logs, much more connections were tried and blocked before a ingame connection fail or success. While in simplewall, 10-15 only in every try, not sure if there is a sort of retry/connection limit there. 

It would be good to find why this is happening, mainly to not get suspended at competitive, first time was 15min, next was an hour.

**Comment by foryVERX** [comment]
My IP Ranges are fine, you have something wrong in your code you need to dig it out. In addition, this is not related to my app. 

Closed.

**Comment by dougg0k** [comment]
Sure they are, but would you be able point out, what would be causing it? Not even in the code itself, but in a choice in the rules perhaps?

**Comment by foryVERX** [comment]
Most likely, it is in the rule created you are missing something or the rules isn't create with correct IP ranges. You need to consider only UDP connections to be reachable for OVERWATCH otherwise you will not be able to connect to all those servers except ones that got the UDP connection during start up. Lastly, what you have said in the comments is very wrong --> "you can press Ctrl+Shift+N and you will see the stats, the IP should be above, you can then use the first 2 decimals and build a range yourself. Use .0.0 in the from and .255.255 in the to. e.g., 35.228.0.0-35.228.255.255".
